jobs:
  - template: /eng/pipelines/templates/jobs/job-matrix.yml
    parameters:
      MatrixConfigs:
        - Name: base_product_matrix
          Path: eng/scripts/job-matrix/samples/matrix.json
          Selection: sparse
        - Name: sdk_specific_matrix
          Path: eng/scripts/job-matrix/samples/matrix.json
          Selection: all
      steps:
        - pwsh:
            Write-Output "SPARSE MATRIX JOB PARAMETERS"
            Write-Output $(Agent.JobName)
            Write-Output "-----------------"
            Write-Output $(operatingSystem)
            Write-Output $(framework)
            try {
              Write-Output $(additionalTestArguments)
            } catch {}
          displayName: Print matrix job variables
          env:
            operatingSystem: $(operatingSystem)
            framework: $(framework)
            additionalTestArguments: $(additionalTestArguments)
        - pwsh: |
            Write-Output "Success"
          displayName: OS condition example
          condition: and(succeededOrFailed(), contains(variables['operatingSystem'], 'windows'))
