resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: azure/azure-sdk-tools
      endpoint: azure
      ref: refs/tags/azure-sdk-tools_20200618.1

jobs:
  - template: /eng/pipelines/templates/jobs/live-test-job.yml
    parameters:
      PreSteps: ${{ parameters.PreSteps }}
      PostSteps: ${{ parameters.PostSteps }}
      EnvVars: ${{ parameters.EnvVars }}
      MaxParallel: ${{ parameters.MaxParallel }}
      BuildInParallel: ${{ parameters.BuildInParallel }}
      TimeoutInMinutes: ${{ parameters.TimeoutInMinutes }}
      ArmTemplateParameters: ${{ parameters.ArmTemplateParameters }}
      Location: ${{ parameters.Location }}
      SubscriptionConfiguration: ${{ parameters.SubscriptionConfiguration }}
      ServiceDirectory: ${{ parameters.ServiceDirectory }}
      ScenarioName: ${{ parameters.ScenarioName }}
