parameters:
  - name: PlatformConfig
    type: string
    default: 'eng/scripts/job-matrix/samples/matrix.json'

jobs:
  - job: generate_matrix
    steps:
    - pwsh: |
        eng/scripts/job-matrix/Create-JobMatrix.ps1 `
          -ConfigPath ${{ parameters.PlatformConfig }} `
          -Selection sparse
      name: generate_job_matrix
      displayName: Generate Job Matrix
  - job:
    dependsOn: generate_matrix
    strategy:
      maxParallel: 0
      matrix: $[ dependencies.generate_matrix.outputs['generate_job_matrix.matrix'] ]
    steps:
      - pwsh: |
          Write-Output "SPARSE MATRIX JOB PARAMETERS"
          Write-Output $(Agent.JobName)
          Write-Output "-----------------"
          Write-Output $(operatingSystem)
          Write-Output $(framework)
          try {
            Write-Output $(additionalTestArguments)
          } catch {}
        displayName: Print matrix job variables
      - pwsh: |
          Write-Output "Success"
        displayName: OS condition example
        condition: and(succeededOrFailed(), contains(variables['operatingSystem'], 'windows'))
