parameters:
  - name: MatrixConfigs
    type: object
    # Example:
    #   - Name: base_product_matrix
    #     Path: /eng/pipelines/matrix.json
    #     Selection: sparse
  - name: steps
    type: object

jobs:
  - ${{ each config in parameters.MatrixConfigs }}:
    - job: generate_matrix_${{ config.Name }}
      displayName: Generate ${{ config.Name }} matrix
      steps:
        - task: PowerShell@2
          displayName: Generate ${{ config.Name }} Job Matrix
          inputs:
            pwsh: true
            workingDirectory: $(Build.SourcesDirectory)
            name: generate_job_matrix_${{ config.Name }}
            filePath: eng/scripts/job-matrix/Create-JobMatrix.ps1
            arguments: -ConfigPath ${{ config.Path }} -Selection ${{ config.Selection }}

    - job:
      displayName: Print ${{ config.Name }}
      dependsOn: generate_matrix_${{ config.Name }}
      strategy:
        maxParallel: 0
        matrix: $[ dependencies.generate_matrix_${{ config.Name }}.outputs['generate_job_matrix_${{ config.Name }}.matrix'] ]
      steps:
        - ${{ parameters.steps }}
