trigger: none


extends:
  template: ../../eng/pipelines/templates/jobs/archetype-sdk-tests-multiple.yml
  parameters:
    ServiceDirectory: keyvault
    TimeoutInMinutes: 120
    EnvVars:
      # Runs samples with live tests.
      AZURE_KEYVAULT_TEST_MODE: Live
    ArmTemplateParameters: "@{ keyVaultDomainSuffix = '.vault.usgovcloudapi.net' }"
